"""Configuration loading, discovery and serialization."""

from __future__ import annotations

import copy
from pathlib import Path

import yaml

from keeper.config.models import AppConfig
from keeper.core.exceptions import ConfigError

DEFAULT_CONFIG_TEXT = """\
# ---------------------------------------------------------------------------
# contributor configuration
# Generated by `keeper init`. See examples/config.example.yaml for notes.
# ---------------------------------------------------------------------------
data_dir: ~/.contributor

schedule:
  start_date: {start_date}
  end_date: {end_date}
  timezone: Africa/Casablanca
  run_time: "08:00"
  commit_count:
    min: 1
    max: 10
  commit_interval:
    min_minutes: 20
    max_minutes: 180
  working_days:
    monday: true
    tuesday: true
    wednesday: true
    thursday: true
    friday: true
    saturday: true
    sunday: false
  branch: main
  dry_run: false
  plan_mode: natural

ai:
  provider: auto
  temperature: 0.7
  max_tokens: 2048
  providers:
    openai:
      api_key: ""
      model: gpt-4o-mini
    gemini:
      api_key: ""
      model: gemini-2.0-flash
    claude:
      api_key: ""
      model: claude-3-5-haiku-latest
    ollama:
      base_url: http://localhost:11434
      model: qwen2.5-coder:7b
    lmstudio:
      base_url: http://localhost:1234/v1
      model: ""
    openrouter:
      api_key: ""
      model: meta-llama/llama-3.1-8b-instruct

safety:
  run_formatter: true
  run_linter: true
  run_tests: false
  test_timeout: 300
  max_changed_files: 15

notifications:
  enabled: true
  desktop: true
  console: false

logging:
  level: INFO
  structured: true
  retention_days: 30

api:
  enabled: true
  host: 127.0.0.1
  port: 8971
"""


def discover_config_path(cwd: Path, data_dir: Path) -> Path | None:
    """Find a config file: cwd/config.yaml, then data_dir/config.yaml."""
    for candidate in (cwd / "config.yaml", data_dir / "config.yaml"):
        if candidate.is_file():
            return candidate
    return None


def load_config(path: Path | None = None) -> AppConfig:
    """Load configuration from an explicit path or by discovery."""
    if path is not None:
        config_path = Path(path).expanduser().resolve()
        if not config_path.is_file():
            raise ConfigError(f"Configuration file not found: {config_path}")
    else:
        data_dir = Path(cwd_data_dir())
        config_path = discover_config(Path.cwd(), data_dir)
        if config_path is None:
            raise ConfigError(
                "No configuration file found. Run `keeper init` before using contributor."
            )
    text = config_path.read_text(encoding="utf-8")
    return AppConfig.parse_text(text, str(config_path))


def cwd_data_dir() -> Path:
    """Compute the default data dir without requiring a config."""
    return Path(Path.cwd() / ".contributor").resolve()


def validate_config(config: AppConfig) -> list[str]:
    """Perform semantic checks on an already-parsed config. Returns warnings."""
    warnings: list[str] = []
    if not config.repositories:
        warnings.append("No repositories configured. Add `repositories[].path` entries.")
    for repo in config.repositories:
        if not Path(repo.path).exists():
            warnings.append(f"Repository path does not exist: {repo.path}")
        elif not (Path(repo.path) / ".git").exists():
            warnings.append(
                f"Path is not a git repository (missing .git): {repo.path}. "
                "It will be reported as unhealthy until initialized."
            )
    return warnings


def generate_default_config(start_date: str, end_date: str) -> str:
    """Render the default config YAML text with the given schedule window."""
    return DEFAULT_CONFIG_TEXT.format(start_date=start_date, end_date=end_date)


def dump_config(config: AppConfig) -> str:
    """Serialize a config model to YAML text."""
    raw = copy.deepcopy(config.model_dump(mode="python"))
    return yaml.safe_dump(raw, sort_keys=False, allow_unicode=True, default_flow_style=False)


def yaml_dump_clean(data: object) -> str:
    """Serialize an arbitrary object to YAML text."""
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False)